### ISSUE TITLE
[bug] [regression] no longer serves public replies on the web

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#3465] opened 2024-10-20 01:58 UTC
### Describe the bug with a clear and concise description of what the bug is.

Used to be I could go to the `https://$instance/…` URI of a public reply I wrote and see it on the web, but this is no longer true, e.g. https://toot.mirbsd.org/@mirabilos/statuses/01JAKGX2SCV4FN125PWDYNMFS9 now gives a 404.

Corresponding log:

```
func=server.init.func1.Logger.13.1 level=INFO latency="833.236µs" userAgent="…" method=GET statusCode=404 path=/@mirabilos/statuses/01JAKGX2SCV4FN125PWDYNMFS9 errors="Error #01: no statuses visible in main thread\n" requestID=b2ma39wj04001bsqw09g msg="Not Found: wrote 1.42kiB"
```

### What's your GoToSocial Version?

0.17.0+git-3ad49f7 🦥

### GoToSocial Arch

amd64 binary

**Comment by mirabilos** [comment] 2024-10-20 01:58
Oh, forgot: I checked the DB and, indeed…

```
gotosocial=# SELECT visibility FROM statuses WHERE id='01JAKGX2SCV4FN125PWDYNMFS9';
 visibility 
------------
 public
(1 row)
```

**Comment by tsmethurst** [comment] 2024-10-20 14:18
If it's a public reply to a non-public or a deleted post that's intended behavior, as there's no "main" thread or main post to show.

**Comment by mirabilos** [comment] 2024-10-20 14:40
On Sun, 20 Oct 2024, tobi wrote:

>If it's a public reply to a non-public or a deleted post that's
>intended behavior, as there's no "main" thread or main post to show.

Hm, okay — just puzzled, as precisely that (unexpectedly) worked
before.

In this case, the initial post was 'unlocked', from a different
user on my instance (maililglist2Fedi bot).

**Comment by tsmethurst** [comment] 2024-10-21 08:33
I'll close this then as it's intended behavior :) Indeed it was a bit weird that it worked before, when it shouldn't have really :')

**Closed by tsmethurst** 2024-10-21 08:33 UTC
Labels: bug
