### ISSUE TITLE
[bug] Boosts are not shown in an accounts homepage

### ISSUE THREAD

**Issue by chri2** [superseriousbusiness/gotosocial#3070] opened 2024-07-04 10:54 UTC
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

The account @nachrichten@hallo.ween.de boosted the post https://botsin.space/@feriencounter_niedersachsen/112726278339689774 .

The post does not appear on the accounts timeline https://hallo.ween.de/@nachrichten .

### What's your GoToSocial Version?

0.16.0+git-f1cbf6f

### Browser version

firefox 127.0.2 (64-Bit)

### What you expected to happen?

I'd expected that the accounts web pages timeline contains all public toots and boosts that a follower would receive.

**Comment by tsmethurst** [comment] 2024-07-04 11:56
Hiya, this is a duplicate of https://github.com/superseriousbusiness/gotosocial/issues/926 so I'll close this one. We'll add a setting to show boosts / unlisted posts at some point.

**Closed by tsmethurst** 2024-07-04 11:56 UTC
Labels: bug, frontend
