### ISSUE TITLE
[feature] Add #Tags support

### ISSUE THREAD

**Issue by StaceyKinder** [superseriousbusiness/gotosocial#1563] opened 2023-02-26 18:06 UTC
### Is your feature request related to a problem ?

Now tags return 404 page

### Describe the solution you'd like.

Return all posts containing this tag

### Describe alternatives you've considered.

NONE

**Comment by tsmethurst** [comment] 2023-02-27 10:03
This is prettymuch a duplicate of https://github.com/superseriousbusiness/gotosocial/issues/967 so I'm gonna close it. Hashtag support is on the roadmap for this year some time, hang in there :)

**Closed by tsmethurst** 2023-02-27 10:03 UTC
Labels: enhancement
