### ISSUE TITLE
[bug] Existing posts from other users aren't visible, even after following them

### ISSUE THREAD

**Issue by ToxicFrog** [superseriousbusiness/gotosocial#1009] opened 2022-11-09 15:33 UTC
### Describe the bug with a clear and concise description of what the bug is.

When you follow someone, their existing posts don't appear in your Home or Federated timelines, or on the user info page in Pinafore/Tusky. New posts they make after you follow them do appear, as far as I can tell.

### What's your GoToSocial Version?

0.5.1-SNAPSHOT git-ad08c6c

### GoToSocial Arch

amd64 docker

### Browser version

Firefox 106.0.2 + pinafore 2.2.1; tusky 19.0

### What happened?

Created a GoToSocial instance, created a single user on it, followed some people. Home and Federated timeline remained empty and clicking on the users I followed in Pinafore showed them as having "0 toots", even though clicking through to their home server shows more than zero.

This morning, posts they made overnight are showing up, but older posts still aren't. For a concrete example, one of my follows, author [Ann Leckie](https://mastodon.annleckie.com/@ann_leckie), is listed as having 12 toots on her home instance, but only 4 if I view her profile through my server.

I believe this to be an issue with GTS itself and not the frontend, since I've reproduced it with both Pinafore and Tusky.

### What you expected to happen?

Posts made by users I follow show up in my Home and Federated timeline even if they made those posts before I followed them.

### How to reproduce it?

- Create a new server
- Create a new user on it
- Follow someone on another server who has already made posts
- Observe that those posts fail to appear on your timeline

It's possible that step 1 is unnecessary and creating a new user on an existing server is sufficient.

### Anything else we need to know?

If this is an intentional limitation to prevent GTS from exploding itself by trying to backfill huge timelines, perhaps a configuration option for how far back (in either post count or time) it should backfill is in order.

**Comment by MDrollette** [comment] 2022-11-09 15:47
Related #266

**Comment by tsmethurst** [comment] 2022-11-10 10:39
Yep yep yep, we just didn't implement backfilling yet :) We'll get to it sooner or later! In the meantime, you can still copy links to posts from the web view of the profile, and post those links in your GtS client's search bar to force your instance to fetch the posts (you might need to search twice, there's a known issue with that rn....)

**Comment by tsmethurst** [comment] 2023-07-31 16:20
I'm gonna close this now since it's more or less a duplicate of https://github.com/superseriousbusiness/gotosocial/issues/266

**Closed by tsmethurst** 2023-07-31 16:20 UTC
Labels: bug, not implemented yet
