### ISSUE TITLE
[feature] S3 storage object prefixing

### ISSUE THREAD

**Issue by peterklipfel** [superseriousbusiness/gotosocial#2202] opened 2023-09-15 16:20 UTC
### Is your feature request related to a problem ?

I would like to be able to specify the "folders" that my gotosocial media is hosted in on S3

### Describe the solution you'd like.

a configuration parameter called `storage-s3-object-prefix` that takes an argument like "path/like/str/"

### Describe alternatives you've considered.

I could just put things in different buckets, but there is a default limit of 100 buckets, and a hard limit of 1000 buckets in S3. So this doesn't scale as well for people who might be running other stuff - i.e. a company that has a "fediverse" bucket. Adding an object prefix seems like a useful addition to the existing system.

**Comment by nyanotech** [comment] 2023-10-31 04:07
Isn't this covered by `storage-s3-bucket`?

```
# String. Name of the storage bucket.
#
# If you have already encoded your bucket name in the storage-s3-endpoint, this
# value will be used as a directory containing your data.
```

**Comment by daenney** [comment] 2024-01-26 10:51
This turns out to be a dupe of #1371, so I'm going to close this one. Feel free to subscribe to the other issue if you're still interested in the feature.

**Closed by daenney** 2024-01-26 10:51 UTC
Labels: enhancement
