### ISSUE TITLE
[bug] Can't follow mastodon account

### ISSUE THREAD

**Issue by peter-jerry-ye** [superseriousbusiness/gotosocial#525] opened 2022-05-02 11:45 UTC
Hello,

When I tried to follow someone on mastodon, I got this message:
```
Could not find the required redirect URL for your account
```
The log of server shows
```
time=2022-05-02T11:42:15Z level=info msg=[7.308003ms] OK: wrote 201 bytes clientIP=172.18.0.3 latency=7.308003ms method=GET path=/.well-known/webfinger?resource=acct:jerryzihye@social.aoxiang.online statusCode=200 userAgent=http.rb/5.0.4 (Mastodon/3.5.1; +https://mastodon.social/)
```
I used the v0.3.1 docker image, and caddy as reverse proxy. Thanks.

**Comment by tsmethurst** [comment] 2022-05-02 13:01
Hi! I tried dereferencing your account from both GoToSocial and Mastodon and it works in both cases. Could you tell me where you're seeing 'Could not find the required redirect URL for your account'? Is that in your Mastodon logs, your client, or in your GoToSocial logs?

**Comment by peter-jerry-ye** [comment] 2022-05-02 13:09
Hi, it was me trying to follow others, who is using a Mastodon, and their site indicates this information.

Take EU Voice as an examle:
![image](https://user-images.githubusercontent.com/16731997/166238877-415d57c6-2805-4149-bad6-0966d4435ad8.png)

**Comment by tsmethurst** [comment] 2022-05-02 13:13
Ahhh okay! We haven't implemented following via the web yet. Could you instead try searching for `@EC_DIGIT@social.network.europa.eu` in whatever client application you're using (tusky? pinafore) and then following from there?

**Comment by peter-jerry-ye** [comment] 2022-05-02 13:20
Thank you for your reply. So I tried with tusky and pinafore and I can follow them. However, it shows 0 toot/tweet and I'm the only subscriber. Is that expected?

![image](https://user-images.githubusercontent.com/16731997/166240446-a33865a7-4874-4f72-8bfb-c14c9d0ff3af.png)

**Comment by tsmethurst** [comment] 2022-05-02 13:22
Yes, that's expected behavior: currently it only shows follower numbers from your instance, and no posts because they haven't sent anything to your instance yet. Once they post something, you will see it on your timeline :)

**Comment by peter-jerry-ye** [comment] 2022-05-02 13:24
Ok, thank you very much for your explanation and thank you for the great work.

Since all is expected, should we close this issue?

**Comment by tsmethurst** [comment] 2022-05-02 13:25
You're very welcome! :) I'll close the issue now, thanks for reporting it. Feel free to reopen this issue or open another issue if you have any more problems.

**Closed by tsmethurst** 2022-05-02 13:25 UTC
Labels: bug
