### ISSUE TITLE
[feature] Register without an email

### ISSUE THREAD

**Issue by coxde** [superseriousbusiness/gotosocial#2980] opened 2024-06-08 22:34 UTC
### Is your feature request related to a problem ?

If I understand [correctly](https://docs.gotosocial.org/en/latest/admin/signups/), at the moment the instance has to configure an email server/service, otherwise you cannot complete the registration process. Personally, I don't like the mandatory requirement to provide an email address for privacy reasons.

### Describe the solution you'd like.

It would be great if the admin could choose whether or not to require an email address on their instance. For smaller instances it might be good to allow registration without email. For larger instances it might be helpful to use email to prevent spam.

### Describe alternatives you've considered.

Another solution would be to keep the email address mandatory, but allow the admin to manually approve it to bypass the email verification using web ui.

### Additional context.

Pleroma provides options for the admin to decide whether email is needed or not.

**Comment by tsmethurst** [comment] 2024-06-10 08:48
For smaller instances, admins can already just manually create users with the CLI and provide any old email address, since users created this way are pre-confirmed and there's no need to use a valid email address there. This is essentially what some admins were already doing before we created this sign-up flow.

> Another solution would be to keep the email address mandatory, but allow the admin to manually approve it to bypass the email verification using web ui.

This is already possible with the CLI :) In future we can add something to the web UI as well for this.

I'm gonna close this since I think it would require some significant code changes for not that much benefit, since there's already alternatives and workarounds in place.

**Closed by tsmethurst** 2024-06-10 08:48 UTC
Labels: enhancement
