### ISSUE TITLE
[feature] mass account follow/import

### ISSUE THREAD

**Issue by nustiueudinastea** [superseriousbusiness/gotosocial#1705] opened 2023-04-17 08:50 UTC
### Is your feature request related to a problem ?

I would like to mass follow/import accounts from a csv. There are various tools online which produce these kind of tools from one’s Twitter account.

### Describe the solution you'd like.

Would be nice to have an API endpoint and a cli command to be able to achieve that.

### Describe alternatives you've considered.

NONE

**Comment by tsmethurst** [comment] 2023-04-19 11:39
Heya, closing this as it's a duplicate of https://github.com/superseriousbusiness/gotosocial/issues/1048

**Closed by tsmethurst** 2023-04-19 11:39 UTC
Labels: enhancement
