### ISSUE TITLE
i18n question

### ISSUE THREAD

**Issue by T1anjiu** [superseriousbusiness/gotosocial#2483] opened 2024-01-03 14:49 UTC
I am not a professional coder，but I want to do something translate for this project.

I read official website's document,README.md,CONTRIBUTING.md etc.

There is no clear place for translation in these documents.(This may be related to my mother tongue is not English.There are still obstacles to overall reading.)

So I want to ask how to join i18n to translate.

I hope someone can get me a solution.

Thanks!
(I really think this may be a problem that I didn't read carefully.I'm really sorry, please give me an answer.)

**Comment by tsmethurst** [comment] 2024-01-03 14:57
Hiya, this is prettymuch a duplicate of https://github.com/superseriousbusiness/gotosocial/issues/474, so I'll close this issue but feel free to continue the discussion there instead.

Basically: we haven't started working on internationalization yet, or put anything in place in terms of templates etc for different languages, because we're still getting basic functionality in place. Not only that, but all the templates and frontend stuff is still very much subject to change. Once things are more stable and settled, we can start looking at translating user facing parts of GtS like web templates, documentation, emails, etc, but it's not an immediate priority.

**Closed by tsmethurst** 2024-01-03 14:57 UTC
