### ISSUE TITLE
Can't follow people on Threads

### ISSUE THREAD

**Issue by johanntan** [superseriousbusiness/gotosocial#3471] opened 2024-10-21 07:57 UTC
### Describe the bug with a clear and concise description of what the bug is.

I can't seam to find any Threads users when I search with semaphore.
My instance in social.jtan.me.
On my Logs it shows something like this.
```
timestamp="21/10/2024 15:56:05.498" func=httpclient.(*Client).DoOnce level=ERROR
 method=GET url=https://threads.net/ap/users/17841459227751075/ attempt="1" requ
estID=rdth7bmj04001dtj4ez0 pubKeyID=https://social.jtan.me/users/johann/main-key
 msg="http response: 500 Internal Server Error"
timestamp="21/10/2024 15:56:05.499" func=server.init.func1.Logger.13.1 level=INF
O latency="1.591816107s" userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv
:131.0) Gecko/20100101 Firefox/131.0" method=GET statusCode=200 path=/api/v2/sea
rch clientIP=172.19.0.1 requestID=rdth7bmj04001dtj4ez0 msg="OK: wrote 59B"
timestamp="21/10/2024 15:56:49.946" func=server.init.func1.Logger.13.1 level=INF
O latency="2.331223ms" userAgent="Mozilla/5.0 (Windows NT 10.0;Win64; x64) Apple
WebKit/537.36 (HTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" method=GET stat
usCode=401 path=/api/v2/search clientIP=172.19.0.1 errors="Error #01: token not
supplied\n" requestID=k0mh9bmj0400023hyf9g msg="Unauthorized: wrote 859B"
```

### What's your GoToSocial Version?

0.17.0+git-3ad49f7  

### GoToSocial Arch

AMD64 Docker

**Comment by tsmethurst** [comment] 2024-10-21 08:30
Afaik threads is probably still not returning AP json in response to our requests, which is the behavior described in https://github.com/superseriousbusiness/gotosocial/issues/2491. I'm gonna close this as a duplicate of that closed issue.

**Closed by tsmethurst** 2024-10-21 08:30 UTC
Labels: bug
