### ISSUE TITLE
[feature] Support native import of Mastodon Export Format into GTS

### ISSUE THREAD

**Issue by sgrigson** [superseriousbusiness/gotosocial#3550] opened 2024-11-19 02:55 UTC
### Is your feature request related to a problem ?

Mastodon gives you this neat export of your posts and data and then lets you do nothing with it.

You'd have thought they'd build a Mastodon importer tool or something, but no.

Of course, I've often fantasized about migrating my entire web presence from Mastodon to GTS.

### Describe the solution you'd like.

Mastodon gives you an export of your posts and then lets you do nothing with it, relying on third-party tools to view your archive, turn it into a static site, or the like. 

The _natural_ thing to do would be to use a Mastodon importer tool, built into Mastodon, to migrate your old posts to a new server, if such was your wish. Mastodon should have built that.

...But they didn't! Haha! Time to scoop the Booby Tooth with an easy post migration tool to GTS. 

"You're on Mastodon? Damn, sucks you have to migrate to a new server. Of course, you can import your posts on GTS. Not sure why you can't do that on Mastodon yet, since it's their export format."

There's probably performance reasons why this is a bad idea to allow willy-nilly, but via server settings or other chicanery we could probably lock this down and of course for a single-user instance they aren't going to care if they are pegging the server while importing all their old data.

This just provides a nice feather in the GTS cap. Literally no one natively supports this right now, and it would encourage others to leave the Mastodonosphere.

There are arguments why you *should* just leave your old posts, or be fine saying goodbye to them, but people have a different relationship with their posts and in my opinion people should be scared that people will leave and take all their data, not be able to hold it hostage, so this fits nicely with the GTS mission.

Later, as a treat, this feature could be a first class 'Migrate from Mastodon' button that essentially clones your account into GTS.

Early versions could just focus on Public and Unlisted posts, exclude replies with mentions (since these probably won't federate properly or will trigger a barrage of notifications).

### Describe alternatives you've considered.

There are of course plenty of tools where you can export your Mastodon archive as a static site. I just think this has a lot of potential to bring positive attention to GTS and make it seem like more of a good jumping off point for people who want to leave, say, mastodon.social and take all their posts with them to a new platform.

**Comment by tsmethurst** [comment] 2024-11-19 21:10
This is a duplicate of https://github.com/superseriousbusiness/gotosocial/issues/2 and https://github.com/superseriousbusiness/gotosocial/issues/896 so I'm going to close it as such.

Also, I understand people's frustration with Mastodon etc, but in future when opening issues please leave out the criticism and contempt for other softwares - it's not relevant to the issue and frankly it's just not very nice.

**Closed by tsmethurst** 2024-11-19 21:10 UTC
Labels: enhancement
