### ISSUE TITLE
[bug] error with s3 configuration in the docker-compose.yaml file?

### ISSUE THREAD

**Issue by fyrfli** [superseriousbusiness/gotosocial#2105] opened 2023-08-12 06:06 UTC
### Describe the bug with a clear and concise description of what the bug is.

Hello GoToSocial team! Love how light this platform is. And I am actually testing it out on my laptop using docker (that's how light this thing is  - have I said that I love it?)

Anyway, I am having issues with configuration... 

I have the following settings in my docker compose file to setup an s3 storage:

```
GTS_STORAGE_BACKEND: "s3"
GTS_STORAGE_S3_ENDPOINT: "my-space.spaces.org"
GTS_STORAGE_S3_USE_SSL: true
GTS_STORAGE_S3_ACCESS_KEY: "access_key"
GTS_STORAGE_S3_SECRET_KEY: "secret_key"
GTS_STORAGE_S3_BUCKET: "bucket-name"
```

But when the container comes up, I get this error message and the container exits:

```
gotosocial  | 2023/08/12 05:48:54 error executing command: error creating storage backend: error opening s3 storage: The specified key does not exist.
```

I have checked and double-checked the variable names (I went as far as copying the names out of the example config.yaml, added the GTS_ prefix, changed them all to uppercase, and changed the dashes to underscores) ... no luck.

Any advice?

### What's your GoToSocial Version?

0.10.0

### GoToSocial Arch

Docker

**Comment by tsmethurst** [comment] 2023-08-12 11:37
Ah thank you! Very odd, we'll check it out :)

**Comment by daenney** [comment] 2023-08-12 14:07
I think this is an error in the configuration, as "The specified key does not exist" is an error emitted by Minio, not GoToSocial. The typical reasons this happens is if the endpoint or use SSL configurations don't match. Are you sure you don't need a port number in your `GTS_STORAGE_S3_ENDPOINT`?

**Comment by daenney** [comment] 2023-08-21 11:14
I'm going to go ahead and close this, as I'm pretty sure it's a configuration issue and not a bug in GtS. If the issue still happens, double-check the endpoint and bucket values. It would also be helpful to know which S3(-like) service you're using, as that might give us a clue as to what's wrong.

**Closed by daenney** 2023-08-21 11:14 UTC
Labels: bug

**Comment by benoliver999** [comment] 2024-02-07 10:37
Sorry to dredge this up but I was getting the same error with DigitalOcean spaces storage. I noticed the OP example says 'spaces' so I wonder if it's the same. 

As far as I can tell there's no good way to set IAM profiles, at least none that I can find on their website. You set up a key and it can access all buckets. I don't know if that's causing the issue.

It _was_ connecting somehow, because if I created a folder inside the bucket with the same name as the bucket, I'd get a different error: `error creating storage backend: error opening s3 storage: EOF`

**Comment by skpy** [comment] 2024-11-06 00:40
Just ran into the same error trying to point to a DigitalOcean Spaces storage bucket.

**Comment by skpy** [comment] 2024-11-06 00:50
I used these values in my docker-compose.yml file:
```
      GTS_STORAGE_BACKEND: "s3"
      GTS_STORAGE_S3_ENDPOINT: "skippy.nyc3.digitaloceanspaces.com"
      GTS_STORAGE_S3_ACCESS_KEY: "<REDACTED>"
      GTS_STORAGE_S3_SECRET_KEY: "<REDACTED>"
      GTS_STORAGE_S3_BUCKET: "fedi"
      GTS_STORAGE_S3_REDIRECT_URL: "https://cdn.skippy.tech"
```

**Comment by fyrfli** [comment] 2024-11-06 03:49
Hmmm ... maybe a DigitalOcean specific thing then? I haven't actually tried it again since...

**Comment by skpy** [comment] 2024-11-06 15:31
I figured it out, I think.

The `storage-s3-endpoint` needs to be the URI of the DigitalOcean Spaces *service* but must not contain the bucket name. Where I had been trying `skippy.nyc3.digitaloceanspaces.com`, it needs to be simply `nyc3.digitaloceanspaces.com`.  Then `storage-s3-bucket` needs to be the bucket name.

I had hoped to be able to use a directory inside a bucket, but including a slash in the `storage-s3-bucket` value resulted in an error.

**Comment by fyrfli** [comment] 2024-11-06 15:46
and you get your instance to start with that adjustment?

**Comment by skpy** [comment] 2024-11-06 16:09
I opened https://github.com/superseriousbusiness/gotosocial/issues/3522 after getting the app running, and finding all my images broken.
