### ISSUE TITLE
[bug] Follow's replies to unfollowed post not showing in home timeline

### ISSUE THREAD

**Issue by pswilde** [superseriousbusiness/gotosocial#2254] opened 2023-10-06 15:09 UTC
### Describe the bug with a clear and concise description of what the bug is.

This may well be expected/desirable behaviour, or I may have configured something somewhere but I've noticed I don't see replies by people I follow on posts from someone I don't follow in the home or federated timeline. If I view the user's profile via my own instance frontend (Semaphore), I see their reply under "Toots and Replies", but I cannot see it anywhere else.
Example in the "What happened?" section

### What's your GoToSocial Version?

0.11.1-SNAPSHOT-git-d173fcd

### GoToSocial Arch

amd64 Container (Podman)

### What happened?

1. User X, who I don't follow, posts a message.
    - I'm not expecting to see this one in my home timeline
2. User Y, who I do follow, replies to User X's post
3. User Y's reply to User X's post is not visible in home or federated timeline, but is visible under that User Y's profile via local frontend

User X and User Y are both on remote instances

### What you expected to happen?

1. User X posts a message - I don't expect to see this
2. User Y replies to User X's message.
3. User X's post shows in my home and federated timelines.

### How to reproduce it?

1. Follow a popular account
2. See posts they make and posts that are replies to others you follow in the home timeline
3. Don't see posts thats are replies to people you don't follow in the home timeline

### Anything else we need to know?

I love you guys! You're doing a great job. Seriously, best instance software out there (and I've used a quite a few at this point!)

**Comment by mirabilos** [comment] 2023-10-07 22:18
I think this is a feature, pretty much. You *can* see them when you zoom into a post, these days.

**Comment by pswilde** [comment] 2023-10-08 07:53
I figured it might be, and that's fine, but as you can't see the post in the first place without going to the either remote users profile... basically there's nothing to "zoom in" on on the home or federated timeline

I noticed as I have a GoToSocial instance and a Pleroma instance following the same people. I thought there was an issue with GtS as it wasn't showing as many posts in the timelines.

**Comment by mirabilos** [comment] 2023-10-08 21:03
Paul Wilde dixit:

>I figured it might be, and that's fine, but as you can't see the post
>in the first place without going to the either remote users profile...
>basically there's nothing to "zoom in" on on the home or federated
>timeline

The original post, no?

>I noticed as I have a GoToSocial instance and a Pleroma instance
>following the same people. I thought there was an issue with GtS as it
>wasn't showing as many posts in the timelines.

Hmm.

Only mildly knowing Twitter first, I actually was *surprised* by
how many replies I had in the home timeline (as opposed to solo
posts or thread starts), and that was before GtS could retrieve
more from the thread when zooming on a post.

Oh well, we’ll see what the authors think.

bye,
//mirabilos

**Comment by tsmethurst** [comment] 2023-10-09 08:09
Heya! That's by design indeed :)

**Comment by pswilde** [comment] 2023-10-09 08:25
OK, not a worry. I understand.
would there be any opening for an option to switch this on from a user-settings perspective?

Personally, I feel like it's more difficult to find new people and see the conversations the people I follow are having this way. 
For example, I'd like to see when someone I follow replies to someone I don't follow about a topic I could be interested in without going directly to their profile pages.

Anyway, as long as it's an intended thing that's fine, I'm not going to start ranting about how it should be a different way or anything 😄

**Comment by pswilde** [comment] 2023-10-09 10:59
> The original post, no?

Just to say thanks again for your input, but no, not from the original post - that's the whole thing. I wouldn't see the original post because I do not follow the person that posted it. I don't expect to see it either :-)

**Comment by tsmethurst** [comment] 2023-10-16 08:56
Given discussion in https://github.com/superseriousbusiness/gotosocial/pull/2261 I'm gonna close this, since the behavior described is intended :)

**Closed by tsmethurst** 2023-10-16 08:56 UTC
Labels: bug
