### ISSUE TITLE
migration from mastodon

### ISSUE THREAD

**Issue by norayr** [superseriousbusiness/gotosocial#447] opened 2022-04-06 10:23 UTC
hello!

i wish i could migrate my mastodon instance to gotosocial.

would you please create a script to migrate the existing mastodon db with users and posts to gotosocial db?

also i guess each instance has its own private key by which it is identified? then also that?

thank you!

**Comment by tsmethurst** [comment] 2022-04-07 07:27
Heya, this is a duplicate of #128 so I'm gonna close it :)

This is something we probably won't work on until GoToSocial is out of alpha and is more feature complete. But it's definitely something we will include when the time comes :)

**Closed by tsmethurst** 2022-04-07 07:27 UTC

**Comment by norayr** [comment] 2022-04-07 15:06
yay yay, thank you!
