### ISSUE TITLE
[bug] Push notifications do not work on Moshidon

### ISSUE THREAD

**Issue by WinsDominoes** [superseriousbusiness/gotosocial#2797] opened 2024-04-02 03:08 UTC
### Describe the bug with a clear and concise description of what the bug is.

There are no push notifications when used with Moshidon on Android

### What's your GoToSocial Version?

v0.14.2

### GoToSocial Arch

amd64 Docker

### What happened?

Moshidon does not send push notifications when using with a GoToSocial Instance

### What you expected to happen?

Push notifications to be sent like normal. 

### How to reproduce it?

Receive a notification on Moshidon using a GoToSocial instance

**Comment by tsmethurst** [comment] 2024-04-02 09:01
Closing this as a dupe of https://github.com/superseriousbusiness/gotosocial/issues/1350 (we just haven't implemented push yet)

**Closed by tsmethurst** 2024-04-02 09:01 UTC
Labels: bug
