### ISSUE TITLE
[bug] Boosts not being shown in Toot!

### ISSUE THREAD

**Issue by DysphoricUnicorn** [superseriousbusiness/gotosocial#954] opened 2022-11-04 16:43 UTC
### Describe the bug with a clear and concise description of what the bug is.

When scrolling my timeline using Toot! I do not see any boosts.  
Others have speculated that this is because GoToSocial does not implement Mastodon's "hide boosts" feature. Apparently for some people it shows boosts as being hidden on all accounts, although it does not do that for me

### What's your GoToSocial Version?

v0.5.2

### GoToSocial Arch

Kubernetes (Docker image running with containerd)

### What happened?

No boosts are shown on my timeline.

### What you expected to happen?

Boosts are shown on my timeline.

### How to reproduce it?

Log into a GTS account using the Toot! app and browse your timeline.

**Comment by jsopsy** [comment] 2023-03-17 22:31
toot v0.33.1 shows boosts in gotosocial 0.7.1 git-adb5966

**Comment by daenney** [comment] 2023-07-09 15:39
This is a thing in Toot!. It hides boosts on GtS. Right now we support toggling the setting, so you can set an account as "not showing boosts" and that setting will be recorded properly. Unfortunately we're not yet filtering the timeline for it. What remains for it is tracked in #999. Once that's in place and released we should reach out to the author of Toot! so they can change the behaviour.

**Comment by tsmethurst** [comment] 2024-01-25 00:25
Hey @DysphoricUnicorn is this still a problem, or should I close this issue now? I think we've implemented everything we needed to to make this work properly :)

**Comment by DysphoricUnicorn** [comment] 2024-01-25 08:48
> Hey @DysphoricUnicorn is this still a problem, or should I close this issue now? I think we've implemented everything we needed to to make this work properly :)

It is still an issue in 13.0, I haven't updated to 13.1 yet

**Comment by daenney** [comment] 2024-01-25 10:38
The issue isn't with GtS anymore, it's been fixed since #2093 which means GoToSocial v0.11 has the fix.

But because that behaviour was broken, Toot! has a built-in behaviour to not show reblogs/boosts in the case of a GtS instance in the timeline. At this point, an update to Toot! would need to be released by @DagAgren to no longer apply that logic on GtS instances running 0.11 or newer. Based on the public changelog in the app store, it doesn't seem there have been any updates to Toot! since March 2023, so it might be a while.

**Comment by daenney** [comment] 2024-01-25 10:44
This feature also works reliably with other clients at this point. I follow a few people that are a bit too trigger happy with boosts for my taste but toggling the "no boosts from this account please" has the desired effect and their boosts no longer make it into my timelines when using Feditext or Tuba, neither of which have explicit code for this when it comes to a GoToSocial instance.

From a GtS standpoint, I don't think there's anything else I can do.

**Comment by DagAgren** [comment] 2024-01-25 12:48
Toot! absolutely has no special case code for GoToSocial. If boosts are not showing, most likely you are sending JSON that is not fully compatible with the Mastodon API spec and fails decoding.

**Comment by daenney** [comment] 2024-01-25 13:07
Ah, odd. I remember researching this for a while and finding a post that explicitly mentioned this. Although now I wonder if this is also a case of Toot vs. Tooot or something and I'm misremembering. My apologies.

**Comment by daenney** [comment] 2024-01-25 13:20
Mm alright, can confirm the behaviour in Toot! of boosts not showing on the home timeline at least, with 0.13.1.

But it works on every other client I use on iOS, including Feditext and Mastodon proper. So if what we're returning is compatible enough that Masto's own client is happy with it, then I'm not sure what we'd have to change to make Toot! happy.

@DagAgren Is there some way I can get a debug build to see what might be causing this?

**Comment by daenney** [comment] 2024-02-01 15:03
My suspicion is that something along the lines of a key being set to `null` vs. empty array `[]`, empty object `{}`, or being absent entirely is what causes this problem. Unfortunately what happens client side is then dependent on the particular JSON parser and how it's configured.

We currently return timelines etc. in a format that's "compatible enough" for other iOS and Android clients to work as expected. This includes the official Mastodon clients (which have no need or incentive to accept anything other than what Masto proper generates).

I'm going to close this one, as without access to the Toot! source code or some debug build so we can figure out what might be tripping it up there's nothing the GtS devs can do about it.

If someone manages to narrow this down, please feel free to reopen the issue.

**Closed by daenney** 2024-02-01 15:03 UTC
Labels: bug
