### ISSUE TITLE
[Documentation/Frontend Tweak] Semaphore no longer dev'd, suggestions for different rec'd frontend(s)

### ISSUE THREAD

**Issue by clarjon1** [superseriousbusiness/gotosocial#3160] opened 2024-07-31 17:57 UTC
Hello! This didnt' feel like a bug or feature request *specifically* so, used the custom dooblydoo. Feel free to tell me which form to use if there's a better one for this!

I'd like to propose the recommendation of different web frontend(s) for users to use with gotosocial instances, as the current recommendation, semaphore, [is no longer being developed, and considered by the dev to be "lights on"](https://fosstodon.org/@semaphore/112075416066363967), with the [git repo being set to read-only](https://github.com/NickColley/semaphore)

If wanting to keep it pivoted to a pinafore based fork, the [enafore fork looks to be under active development still](https://github.com/enafore/enafore), which appears to be being developed with a focus on compatibility with non-vanilla masto-compatible server backends, which may be useful given that gotosoc fits that category.

I've personally been loving the [phanpy frontend](https://phanpy.social/) paired to my personal instance, and their docs [include a list of alternative web frontends](https://github.com/cheeaun/phanpy?tab=readme-ov-file#alternative-web-clients) for consideration!

**Comment by tsmethurst** [comment] 2024-08-01 17:54
Personally I'd rather keep the semaphore recommendation, or even go back to recommending pinafore (also unmaintained). The fact it's not actively being developed doesn't make it any less good in it's current form, imo, and if the site goes down at some point we can host an instance of it ourselves somewhere so people can still use it. Issues with some other clients are:

1. they're not up to the same level of usability for screenreader users, based on feedback we've heard, and that includes enafore, which apparently introduced some regressions in terms of screenreader usability. Pinafore/semaphore are still definitely the best in this regard.
2. Some of them do some pretty odd things like have the user's browser call other instance APIs directly (instead of going through their host instance), which is not really great since it can cause the user's browser to make api calls to instances that have been blocked by the gts server.
3. In terms of being fast and lightweight in the browser, I don't think there's a web client better than pinafore/semaphore unless you count something like brutaldon.

If those issues are resolved I think we could probably switch recommendations to another client, but for now I (personally) think it's fine to just make the user aware of other clients by saying "hey try one of these other mastodon clients (link to masto website), they might work", which is what we already do.

**Comment by tsmethurst** [comment] 2024-12-02 09:47
Related: https://github.com/superseriousbusiness/gotosocial/pull/3586 -- we're now recommending pinafore again since it still receives some very basic updates and stuff.

**Comment by tsmethurst** [comment] 2024-12-08 15:00
I'm gonna close this in light of the above. We can reopen it again later if necessary but I honestly think it's fine to keep recommending pinafore for now.

**Closed by tsmethurst** 2024-12-08 15:00 UTC
Labels: documentation
