### ISSUE TITLE
/users/:username always met with unauthorized

### ISSUE THREAD

**Issue by geekgonecrazy** [superseriousbusiness/gotosocial#403] opened 2022-02-18 04:20 UTC
I've got gotosocial setup with Traefik and kubernetes using the superseriousbusiness/gotosocial docker image.

I login using pinafore.  Then try to follow my mastodon account and I get this:

```
time=2022-02-18T04:05:59Z level=info msg=[14.24µs] No Content: wrote 0 bytes clientIP=10.42.0.28 latency=14.24µs method=OPTIONS path=/api/v1/accounts/01BJZDRCY0EQF3PEBAN3HSBBXY/follow statusCode=204 userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
time=2022-02-18T04:06:00Z level=info msg=[329.920769ms] OK: wrote 263 bytes clientIP=10.42.0.28 latency=329.920769ms method=POST path=/api/v1/accounts/01BJZDRCY0EQF3PEBAN3HSBBXY/follow statusCode=200 userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
time=2022-02-18T04:06:00Z level=info msg=[2.515699ms] OK: wrote 816 bytes clientIP=10.42.0.28 latency=2.515699ms method=GET path=/users/aaron/main-key statusCode=200 userAgent=http.rb/5.0.4 (Mastodon/3.4.6; +https://fosstodon.org/)
time=2022-02-18T04:06:02Z level=info msg=not authorized func=UsersGETHandler url=/users/aaron
time=2022-02-18T04:06:02Z level=info msg=[667.59491ms] Unauthorized: wrote 42 bytes clientIP=10.42.0.28 latency=667.59491ms method=GET path=/users/aaron statusCode=401 userAgent=http.rb/5.0.4 (Mastodon/3.4.6; +https://fosstodon.org/)
time=2022-02-18T04:06:02Z level=error msg=batch deliver had at least one failure: POST request to https://fosstodon.org/users/geekgonecrazy/inbox failed (401): 401 Unauthorized
time=2022-02-18T04:06:02Z level=info msg=[1.518212ms] OK: wrote 3157 bytes clientIP=10.42.0.28 latency=1.518212ms method=GET path=/fileserver/01BJZDRCY0EQF3PEBAN3HSBBXY/attachment/original/0131CG1WN2VNVZJ1M9VKP06Y3Y.jpeg statusCode=200 userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
```

I'm attempting to follow my @geekgonecrazy@fosstodon.org account.  Looks like when fosstodon.org tries to get info back it rejects.

Same happens if I try to search for my gotosocial account from fosstodon.org

```
time=2022-02-18T04:11:04Z level=info msg=[1.464577ms] OK: wrote 425 bytes clientIP=10.42.0.28 latency=1.464577ms method=GET path=/.well-known/webfinger?resource=acct:aaron@test-gotosocial.geekgonecrazy.com statusCode=200 userAgent=http.rb/5.0.4 (Mastodon/3.4.6; +https://fosstodon.org/)
time=2022-02-18T04:11:05Z level=info msg=not authorized func=UsersGETHandler url=/users/aaron
time=2022-02-18T04:11:05Z level=info msg=[559.053133ms] Unauthorized: wrote 42 bytes clientIP=10.42.0.28 latency=559.053133ms method=GET path=/users/aaron statusCode=401 userAgent=http.rb/5.0.4 (Mastodon/3.4.6; +https://fosstodon.org/)
```

I'm running in kubernetes with the following environment variables set:
```
- name: GTS_HOST
  value: test-gotosocial.geekgonecrazy.com
- name: GTS_ACCOUNT_DOMAIN
  value: test-gotosocial.geekgonecrazy.com
- name: GTS_PORT
  value: "8080"
- name: GTS_STORAGE_LOCAL_BASE_PATH
  value: /gotosocial/storage
- name: GTS_DB_TYPE
  value: sqlite
- name: GTS_DB_ADDRESS
  value: /gotosocial/db/gotosocial.db
```

can replicate with docker something like: 
`docker run -d --name gotosocial -p 8080:8080 -e GTS_HOST={host} -e GTS_ACCOUNT_DOMAIN={host} -e GTS_PORT=8080 -e GTS_STORAGE_LOCAL_BASE_PATH=/gotosocial/storage -e GTS_DB_TYPE=sqlite -e GTS_DB_ADDRESS=/gotosocial/db/gotosocial.db -v $PWD/gotosocial.db:/gotosocial/db/gotosocial.db superseriousbusiness/gotosocial`

Then I hop in to the container and created account using the CLI
```
docker exec -it gotosocial /gotosocial/gotosocial admin account create --username aaron --email my-email  --password SuP3rS3Cur3
docker exec -it gotosocial /gotosocial/gotosocial admin account confirm --username aaron
docker exec -it gotosocial /gotosocial/gotosocial admin account promote --username aaron
```

**Comment by geekgonecrazy** [comment] 2022-02-18 05:31
Ah! This might be because I had attempted to look it up from mastodon when app domain wasn't set and I wiped database and started again.. 

Which I read in one of issues there is something related to keys and the remote keeping old keys?

**Comment by tsmethurst** [comment] 2022-02-18 08:49
Heya! This is caused by a bug introduced in the latest version of Mastodon. See known issues in the release notes of GtS: https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.2.0

Basically, Mastodon uses their instance actor for lots of stuff (to group delivery of messages, to dereference accounts, that kind of thing). The bug that was introduced prevents the instance actor from being dereferenced. So what's happening is, Mastodon sends a message to GtS, or vice versa, and GtS attempts to dereference the public key of the Mastodon instance actor, to verify the http-signed activitypub message. Because the instance actor cannot be dereferenced, GoToSocial has no way of verifying that the request it received actually came from the Mastodon instance in question, and so it returns a 401 to Mastodon.

This has already been fixed by Mastodon, but the fix is not yet in a release, unfortunately, so there's nothing we can do about it from our side :(

**Comment by tsmethurst** [comment] 2022-02-28 11:17
I'm gonna close this now since it's not something we can fix on our side.

**Closed by tsmethurst** 2022-02-28 11:17 UTC

**Comment by norayr** [comment] 2022-06-17 14:40
i just opened similar issue in socialhome issue tracker: https://gitlab.com/jaywink/socialhome/-/issues/616

socialhome also has troubles federating and even searching for gotosocial users.

logs at the link above.

it is likely to be a gotosocial issue.

**Comment by tsmethurst** [comment] 2022-06-18 15:36
Hi @norayr, I looked at the issue you linked, and from the logs posted there it looks as though socialhome isn't signing requests using http signatures. GoToSocial requires http signatures on all federating requests and dereference requests, otherwise it will not serve the requests (hence the 401 unauthorized that you see in the logs).

**Comment by norayr** [comment] 2022-06-18 16:16
oh thank you so much for reply! i will quote it at socialhome gitlab issue.
