### ISSUE TITLE
[bug] Invalid JSON-LD contexts

### ISSUE THREAD

**Issue by grishka** [superseriousbusiness/gotosocial#3230] opened 2024-08-24 18:58 UTC
### Describe the bug with a clear and concise description of what the bug is.

I'm sorry but Smithereen seems to be the only ActivityPub server that actually implements JSON-LD for real, and this context is not valid:
![Снимок экрана 2024-08-24 в 21 40 37](https://github.com/user-attachments/assets/2f611a3a-9c0c-45bd-8369-61b14584647c)

### What's your GoToSocial Version?

0.16.0+git-f1cbf6f

### What you expected to happen?

The URLs you put into that array are meant to be remote contexts, i.e. pointing to a JSON-LD file that has a `@context` in it. Two of the four in your context aren't those, they are namespaces. You want to have aliases to them, like so:
```json5
{
    "@context": [
        "https://www.w3.org/ns/activitystreams",
        "https://w3id.org/security/v1",
        {
            "sc": "http://schema.org#",
            "toot": "http://joinmastodon.org/ns#",
            /* aliases to names that you use from these namespaces, for example: */
            "Emoji": "toot:Emoji"
        }
    ],
    /* the rest of the object */
}
```
It's the same idea as XML namespaces but richer.

### Anything else we need to know?

The original issue that prompted this investigation: https://github.com/grishka/Smithereen/issues/77

The actor I'm testing with is `@sl@gts.sadium.cyou`.

**Comment by tsmethurst** [comment] 2024-08-25 08:31
Closing as duplicate of https://github.com/superseriousbusiness/gotosocial/issues/1947

**Closed by tsmethurst** 2024-08-25 08:31 UTC
Labels: bug
