### ISSUE TITLE
[bug] brutalist theme may crash webpage on webkit iOS

### ISSUE THREAD

**Issue by technokatzen** [superseriousbusiness/gotosocial#3279] opened 2024-09-08 15:28 UTC
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

The brutalist theme or something on the first page of @/tobi's personal timeline crashes WebKit on iPhone 11 Pro, iOS 17.6.1

I checked out the brutalist theme at the following link: http://goblin.technology/@tobi

It visually glitches quite a lot on first load (unfortunately subsequent loads, even when deleting the cache, don't cause the visual glitches, so I didn't get it on video) then the page crashes.

Here's a video in Vivaldi and safari:

https://github.com/user-attachments/assets/392e6e20-c9e7-4f12-9f62-dfb4eda8aae4

https://github.com/user-attachments/assets/b93750ec-47bd-4e69-9d72-1b6a2bf575ff

### What's your GoToSocial Version?

? Page crashes before I can read it

### Browser version

Safari 17.6.1

### What happened?

In loading the webpage visually glitches (not the CSS or anything, but the browser itself) then crashes.

### What you expected to happen?

I would expect the browser not to crash. 

### How to reproduce it?

Open the provided link to Tobi's profile, it reliably crashes for me, about 90% of the time.

### Anything else we need to know?

Honestly it may be something else on the page that is causing the crash but I'm really not sure.

I will try to get more debug information from the page with safari desktop and update this issue once I have.

**Comment by tsmethurst** [comment] 2024-09-08 15:41
Damn, that's a hell of a brutal theme indeed.

**Comment by tsmethurst** [comment] 2024-09-08 15:47
I've no idea what might be causing this. I tried it on another Webkit browser (Gnome Epiphany) and it works with no issues. No warnings logged on Chrome or Firefox either. A head-scratcher.

**Comment by technokatzen** [comment] 2024-09-08 16:26
I'll try to figure out how to get debug info from safari when I have time in the next couple days then, before iOS 18 releases (and also let y'all know if it continues happening afterwards)

**Comment by daenney** [comment] 2024-09-09 10:50
I can reproduce this on iOS 17.6.1.

**Comment by tsmethurst** [comment] 2024-09-09 10:55
What happens if you open a different page that also has the theme set, for example https://goblin.technology/@tobi/statuses/01HS67TV92QPXTY1276G6TXPPD ?

**Comment by daenney** [comment] 2024-09-09 12:30
That one's fine. I've had it open and scrolled around for a minute or so, no crashes. Something about the profile page does it.

**Comment by tsmethurst** [comment] 2024-09-09 13:43
My guess would be that it's the 25MB webm in my pinned posts, but there's nothing particularly unusual about a page containing a 25MB webm video. Unless we can get some logs from safari showing that we're doing something wrong, I'm tempted to chalk this up to a Safari bug.

**Comment by Fastidious** [comment] 2024-09-09 14:53
I use Safari under iOS 17.6.1, and cannot replicate.

**Comment by tsmethurst** [comment] 2024-09-16 09:48
I'm gonna close this since I think it's most likely not a GtS issue specifically, but if anyone can gather logs that would point to something we can fix, please feel free to reopen.

**Closed by tsmethurst** 2024-09-16 09:48 UTC
Labels: bug, frontend
