### ISSUE TITLE
[feature] option to remove an avatar/banner

### ISSUE THREAD

**Issue by selfisekai** [superseriousbusiness/gotosocial#3405] opened 2024-10-08 08:19 UTC
### Is your feature request related to a problem ?

once a user avatar or banner is set, it can't be simply removed. not sure if an API is missing, or just the frontend feature?

### Describe the solution you'd like.

"Remove" button next to upload in `/settings/user/profile`

### Describe alternatives you've considered.

none

**Comment by tsmethurst** [comment] 2024-10-08 08:40
Hiya! Indeed we just lack a "remove" button in the settings panel. Something to be added for 0.18.0 most likely. I'm gonna close this as it's a duplicate of https://github.com/superseriousbusiness/gotosocial/issues/823, where we're already tracking this :)

**Closed by tsmethurst** 2024-10-08 08:40 UTC
Labels: enhancement
