### ISSUE TITLE
[bug] Can not follow some account

### ISSUE THREAD

**Issue by whtiehack** [superseriousbusiness/gotosocial#1070] opened 2022-11-18 06:24 UTC
### Describe the bug with a clear and concise description of what the bug is.

Can follow some users

![image](https://user-images.githubusercontent.com/12741016/202631778-878102c2-47c6-404f-bba1-ce6bac5566f5.png)

But some unlock people cannot follow, only show follow requested

![image](https://user-images.githubusercontent.com/12741016/202632096-2f485784-f7a8-4e84-9519-7dc15d269bd4.png)

this is also unlock user.
![image](https://user-images.githubusercontent.com/12741016/202635162-bdeff279-eb49-4f85-ad98-8c8d75506ea7.png)

### What's your GoToSocial Version?

0.5.2

### GoToSocial Arch

amd64

### Browser version

Edg/107.0.1418.42

### What happened?

cannot follow unlock user.

### What you expected to happen?

can follow unlock user.

### How to reproduce it?

Just run a new instance.

and my instance environment is use caddy for reverse proxy, and use cloudflare as cdn

![image](https://user-images.githubusercontent.com/12741016/202634934-9c8b40a9-e9fd-4f01-9fd3-a87203a01c0e.png)

**Comment by tsmethurst** [comment] 2022-11-18 09:49
This issue can be caused by flakey federation or lots of load on the remote instance. Try unfollowing and following again, and wait a bit and see if the follow goes through.

**Comment by whtiehack** [comment] 2022-11-18 12:54
> This issue can be caused by flakey federation or lots of load on the remote instance. Try unfollowing and following again, and wait a bit and see if the follow goes through.

the `mastdn.social` problem was server overload, but the `@help@ovo.st` still cannot follow.


https://user-images.githubusercontent.com/12741016/202709850-981ca65f-ce36-451a-9b79-1c8717d943cc.mp4

**Comment by tsmethurst** [comment] 2022-11-19 09:16
hmm, what is ovo.st? it's not an implementation i've seen before: it might be worth raising this issue with them to see if they can debug it from their end :)

**Comment by whtiehack** [comment] 2022-11-19 14:02
> hmm, what is ovo.st? it's not an implementation i've seen before: it might be worth raising this issue with them to see if they can debug it from their end :)

ok, I'll try it.

**Comment by tsmethurst** [comment] 2022-11-21 12:58
If it's OK with you, i'm going to close this issue; if you wanna raise another one later for interoperability with ovo.st that would be welcome :)

**Closed by tsmethurst** 2022-11-21 12:58 UTC
Labels: bug
