### ISSUE TITLE
[feature] Show Description and Terms of an instance on the landing page

### ISSUE THREAD

**Issue by object-required** [superseriousbusiness/gotosocial#1328] opened 2023-01-12 01:37 UTC
### Is your feature request related to a problem ?

_Full description_ of an instance can be edited at `settings/admin/instance-settings` but is not displayed anywhere. It might be beneficial to display it under the _short description_ on the landing page.

### Describe the solution you'd like.

Extend `web/templates/index.tmpl` with `instance.Description`.

### Describe alternatives you've considered.

One option is to edit `web/templates/index.tmpl` template manually for a particular instance.

Cramping everything into short description is also possible because it accepts HTML:
https://github.com/superseriousbusiness/gotosocial/blob/main/internal/processing/instance.go#L184-L191

### Additional context.

- The landing page itself was created in #32
- The `instance.Terms` _Terms & Conditions_ is not printed as well, it may be convenient to add it too

**Comment by tsmethurst** [comment] 2023-01-12 13:09
Closing this as a duplicate of https://github.com/superseriousbusiness/gotosocial/issues/143

**Closed by tsmethurst** 2023-01-12 13:09 UTC
Labels: enhancement
