### ISSUE TITLE
[bug] /settings/admin/settings does not load all existing settings

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2610] opened 2024-02-06 15:33 UTC
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

When I go to `/settings/admin/settings` on my instance, only some things are filled in (title, avatar image, avatar description, contact user), whereas others I know I had filled (and/or which `/api/v1/instance` currently reports), namely short and full description, are not shown.

### What's your GoToSocial Version?

0.13.1-SNAPSHOT git-b6fe8e7 🦥

### Browser version

Firefox 115.7.0esr (Debian/amd64)

**Comment by mirabilos** [comment] 2024-02-06 18:22
Aaaah, okay.

Have you considered collecting all the release notes in a say .md file in the source tree? That way you could collect those for the development branch there as well, for both users of snapshots and so you can then simply copy/paste when releasing (and add the usual part about database migrations, config, etc).

**Comment by mirabilos** [comment] 2024-02-06 18:28
oic `/api/v1/instance` got new `{,short_}description_text` fields that contain Markdown now, and `{,short_}description` are supposed to contain HTML.

Well, they contain HTML-ish (`**` became `<strong>`), but in contrast to before, `&` is not properly escaped to `&amp;`, so something is not quite ready yet…

**Comment by tsmethurst** [comment] 2024-02-06 21:08
I'll close this now since it was not a bug.

> & is not properly escaped to &amp;

Looks like a separate issue, this is already present in our markdown parser for a long time afaict, so not related to the code mentioned above. Hasn't caused us any problems so far, which is probably why it's not been noticed. Opened an issue here: https://github.com/superseriousbusiness/gotosocial/issues/2612

> Have you considered collecting all the release notes in a say .md file in the source tree

Considered it yes, can't be arsed currently but maybe later.

**Closed by tsmethurst** 2024-02-06 21:08 UTC
Labels: bug, frontend

**Comment by mirabilos** [comment] 2024-02-07 09:41
tobi dixit:

>I'll close this now since it was not a bug.

OK.

>> & is not properly escaped to &amp;
>
>Looks like a separate issue, this is already present in our markdown
>parser for a long time afaict, so not related to the code mentioned

Oh!

Isn’t that a bug in the Markdown library then, to not escape them? Meh.

If you want to paper over these later, valid entities match

/[&](?:#[0-9]+|#x[0-9a-fA-F]+|[:A-Z_a-zÀ-ÖØ-öø-˿Ͱ-ͽͿ-῿‌‍⁰-↏Ⰰ-⿯、-퟿豈-﷏ﷰ-�𐀀-󯿿][:A-Z_a-zÀ-ÖØ-öø-˿Ͱ-ͽͿ-῿‌‍⁰-↏Ⰰ-⿯、-퟿豈-﷏ﷰ-�𐀀-󯿿.0-9·̀-ͯ‿-⁀-]*);/

Any & not matching that needs to be &amp; though with the
lack of support for lookahead, that’s a but tricky.

>> Have you considered collecting all the release notes in a say .md
>> file in the source tree
>
>Considered it yes, can't be arsed currently but maybe later.

Thanks! No worries about now, that was just a wild improvement idea.

Have a nice day,
//mirabilos
