### ISSUE TITLE
[bug] Authentication error for Desk App

### ISSUE THREAD

**Issue by huggenknubbel** [superseriousbusiness/gotosocial#1170] opened 2022-11-29 09:13 UTC
### Describe the bug with a clear and concise description of what the bug is.

Error while authentication with [the Desk](https://thedesk.top/en/) App (web or native) 
after login successfully and click on "authorize" i got the Error: 

`Bad Request: key response_type was not found in session: key client_id was not found in session: key redirect_uri was not found in session: key scope was not found in session: key userid was not found in session: If you arrived at this error during a login/oauth flow, please try clearing your session cookies and logging in again; if problems persist, make sure you're using the correct credentials`

### What's your GoToSocial Version?

0.5.2

### GoToSocial Arch

Binary

### Browser version

 Microsoft Edge Version 107.0.1418.56 (64-Bit)

**Comment by tsmethurst** [comment] 2022-11-29 10:38
Can you try again with the latest release candidate of GtS? if the issue is what I think it is, it's fixed now

**Comment by huggenknubbel** [comment] 2022-11-29 10:48
nice, its fixed now! 
Thanks mate!

**Comment by tsmethurst** [comment] 2022-11-29 13:39
Grand :)

**Closed by tsmethurst** 2022-11-29 13:39 UTC
Labels: bug

**Comment by tyrosinase** [comment] 2023-10-07 23:10
Hmm, I'm getting the same thing in `GoToSocial 0.11.1 git-c7a46e0` (though with LWP::UserAgent making the request).
