### ISSUE TITLE
[frontend] Showing unlisted toots in webview

### ISSUE THREAD

**Issue by f0x52** [superseriousbusiness/gotosocial#176] opened 2021-08-30 19:46 UTC
[to be discussed]

imo yes because it tracks with how I use unlisted posting myself, ie show to everyone but don't put it on Local + Federated TL directly. And it matches how other implementations handle this type of status (so you could view it through an other instance anyways)

**Comment by tsmethurst** [comment] 2021-08-31 09:01
My reason for not wanting to show unlisted toots in web view was that I wanted to provide users with a way of selecting whether or not they wanted to show a public/unauthenticated web view for a status, *without* having to mark that status as followers-only or more restrictive.

So I was initially leaning towards *not* showing unlisted toots in webview. But from a strictly activitypub point of view, that doesn't *really* make sense because unlisted toots are actually CC to public. Not that there's an obligation to show a web view for anything, according to AP, mind you.

So I'm in two minds here. I do want to make web views optional, but i also don't want us to add too many switches and toggles, but I *also* don't want to break expected behavior.

**Comment by f0x52** [comment] 2021-08-31 09:05
I think an account-wide toggle would be a good compromise, something like
"Show my public and unlisted toots on the web. Note that other instances might show these statuses regardless of the setting"

Same for showing (toots on) your profile page

**Comment by tsmethurst** [comment] 2021-09-03 09:50
This makes sense. I will close this one then :)

**Closed by tsmethurst** 2021-09-03 09:50 UTC
Labels: frontend
