### ISSUE TITLE
[bug] Incorrect user count on status page

### ISSUE THREAD

**Issue by mhils** [superseriousbusiness/gotosocial#2727] opened 2024-03-06 15:49 UTC
### Describe the bug with a clear and concise description of what the bug is.

https://fedi.hi.ls/about shows "home to 2 users", but there is only one user on the instance.

### What's your GoToSocial Version?

0.14.0

### GoToSocial Arch

amd64 Docker

### How to reproduce it?

I unfortunately don't have a reproducer for this, but maybe the following helps: The user count seems to be derived from https://github.com/superseriousbusiness/gotosocial/blob/v0.14.0/internal/db/bundb/instance.go#L41. Based on that, I looked at my sqlite database and found an additional "friendica" user without a domain.

```sql 
> SELECT username FROM accounts WHERE domain IS NULL;
fedi.hi.ls
max
friendica
```

I never created a "friendica" account. Opening https://fedi.hi.ls/@friendica yields an internal server error with the following in the logs:

```
fedi.hi.ls_1             | timestamp="06/03/2024 15:48:05.501" func=server.glob..func1.Logger.func13.1 level=ERROR latency="6.347079ms" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" method=GET statusCode=500 path=/@friendica clientIP=172.17.0.9 errors="Error #01: error converting account: AccountToAPIAccountPublic: error getting user from database for account id 01HGFTKZ5WV5GX1FPWNJ8WVFTJ: sql: no rows in result set\n" requestID=ys87654e04000e5zzm2g msg="Internal Server Error: wrote 946B"
```

Thank you for your fantastic work on GoToSocial! 🍰 ❤️

**Comment by tsmethurst** [comment] 2024-03-06 17:10
Hiya, this looks like a duplicate of https://github.com/superseriousbusiness/gotosocial/issues/2515, caused by https://github.com/superseriousbusiness/gotosocial/issues/2474

I believe we've fixed our logic to not store those accounts, now, but we still haven't written a migration to safely remove them.

I'll close this as it's a duplicate, but we'll make sure to include a migration for the issue in 0.15.0 :)

**Closed by tsmethurst** 2024-03-06 17:10 UTC
Labels: bug

**Comment by mhils** [comment] 2024-03-06 18:52
Thanks for the prompt reply and sorry for not searching the issue tracker properly. I somehow missed both of them. Thank you! 🍰
