### ISSUE TITLE
[bug] Seeing 401 errors when communicating when GTS instances

### ISSUE THREAD

**Issue by mejofi** [superseriousbusiness/gotosocial#2466] opened 2023-12-17 16:39 UTC
### Describe the bug with a clear and concise description of what the bug is.

A recent version of GTS seems to have introduced a change that yields 401 errors on the Mastodon side, where those did not happen before.

### What's your GoToSocial Version?

unknown

### GoToSocial Arch

unknown

### What happened?

The `ActivityPub::FetchRepliesWorker` on Mastodon, version 4.2.1 and 4.2.3, yields the following error when talking to various GTS instances, including the official one;

`Mastodon::UnexpectedResponseError: https://gts.superseriousbusiness.org/users/gotosocial/statuses/01HHW85D4ENBNJTJP49QQVDPCS/replies?limit=20&only_other_accounts=true returned code 401`

This results in dead jobs in the Mastodon Sidekiq queue, from a number of different GTS instances. It does not happen with any other instance types.

### What you expected to happen?

For this to work without errors.

### How to reproduce it?

This happens during normal operation, apparently whenever a new post gets published from a GTS instance, and it is viewed from our side.

### Anything else we need to know?

This started happening a week or two, maybe? Our Mastodon version was 4.2.1 at the time, and had not changed in a while, so it's unlikely that it is a change on the Mastodon side. It still occurs with the 4.2.3 release.

**Comment by smiba** [comment] 2023-12-18 09:49
Having the same issue, my sidekiq queue is full of dead jobs with the same issue all from GTS instances. Only started to happen since 1-2 weeks

**Comment by NyaaaWhatsUpDoc** [comment] 2023-12-18 13:42
This is to be expected. GoToSocial uses a slightly different httpsig specification to Mastodon (technically Mastodon's is outdated) so endpoints with query parameters will return 401 since Mastodon doesn't sign them correctly. Even if the spec that Mastodon aligns with is outdated, it seems to be the one that is most used so GoToSocial will be adding a compatibility fix for this sometime in the new year.

We already have numerous linked issues you can find in the original issue thread here: https://github.com/superseriousbusiness/gotosocial/issues/894

And the relevant Mastodon project issue: https://github.com/mastodon/mastodon/issues/18638

(as for why Mastodon is deciding that it should retry on a returned 401 code? that actually sounds more like a Mastodon bug).

**Comment by NyaaaWhatsUpDoc** [comment] 2023-12-18 13:50
i'm not 100% sure why you're only seeing this recently, i do have a few possible explanations though nothing concrete. my guess is that if there was a change, it was a change to *more correct* behaviour if anything, (or that's my hunch). because those 401s are to be expected from mastodon querying our /replies endpoint

**Comment by NyaaaWhatsUpDoc** [comment] 2023-12-18 13:55
mastodon actually has an open PR for a fix on their side it turns out, though it seems to be gathering dust at the moment: https://github.com/mastodon/mastodon/pull/18474

**Comment by smiba** [comment] 2023-12-18 13:56
Agreed, if it's a signing issue from mastodon's side then this is expected behaviour so no complaints about GTS from my side. 

![zabbix__History__refreshed_every_30_sec__](https://github.com/superseriousbusiness/gotosocial/assets/3308142/3a26fa4c-e317-4568-96b4-e59968d1d8d2)

Looking at our monitoring I can't figure out where this started either. on the 16th of November we could still properly retry the queue and be only left with instances that are down or misconfigured. Around the 18th of November it seems there to be a lot more growth from that point onwards, almost all 401 errors from GTS instances. 

Either way, it's expected behaviour like you said so I'll point my attention towards mastodon for this issue, thanks!

**Comment by tsmethurst** [comment] 2023-12-18 14:33
It's also worth noting that there are more GtS instances running than before. So that's another possible reason for seeing more of these errors than earlier.

Re: the spec, I looked through it again recently and it's *VERY* ambiguous (to my mind, at least) whether or not URL query parameters should or shouldn't be included in the signature. Here's the link: https://www.rfc-editor.org/rfc/rfc9113#section-8.3.1-2.4.1

> The ":path" pseudo-header field includes the path and query parts of the target URI (the absolute-path production and, optionally, a '?' character followed by the query production; see [Section 4.1](https://www.rfc-editor.org/rfc/rfc9110#section-4.1) of [[HTTP](https://www.rfc-editor.org/rfc/rfc9113#RFC9110)]).

So it says it "includes the path and query parts", all well and good, but it also says "optionally, a ? character blah blah". I don't wanna get into semantics too much, but I can very much understand why Mastodon and others don't include it, and I also understand why the library we depend on for our signatures does include it :P

But yeah, we'll be working on fallback behavior that implements both ways of interpreting the spec.

**Comment by daenney** [comment] 2024-01-07 11:12
I'm going to close this one since:
* Masto leaving 401s in to retry isn't something GtS can fix
* Masto has improved the situation with mastodon/mastodon#28476
* Improvements we want to make to http sig interoperability is already tracked in #894

**Closed by daenney** 2024-01-07 11:12 UTC
Labels: bug
