### ISSUE TITLE
[feature] Support for custom account aliases

### ISSUE THREAD

**Issue by saghul** [superseriousbusiness/gotosocial#1693] opened 2023-04-11 07:00 UTC
### Is your feature request related to a problem ?

I'm trying to migrate my account from a Mastodon server to my self-hosted GtS instance. One of the steps to make this process seamless is to add an alias to the old account in the new one, which AFAICT GtS does not seem to support.

### Describe the solution you'd like.

I'd like to be able to add an account alias to facilitate the migration of my account.

### Describe alternatives you've considered.

None

**Comment by daenney** [comment] 2023-04-11 08:02
GtS doesn't support account mobility yet, specifically the `move` activity #130.

This is essentially a dupe of that issue, as the `alsoKnownAs` alias is one of the many pieces we need to put in place for that. I would suggest closing this issue and subscribing to #130 instead.

**Closed** 2023-04-11 08:35 UTC
Labels: enhancement
