### ISSUE TITLE
[bug] Following always shows pending

### ISSUE THREAD

**Issue by Fastidious** [superseriousbusiness/gotosocial#1184] opened 2022-11-30 00:27 UTC
### Describe the bug with a clear and concise description of what the bug is.

Following a remote user will always show the follow button as “pending”, even though the remote user have following open. 

### What's your GoToSocial Version?

v0.6.0-rc1

### GoToSocial Arch

amd64

### Browser version

Safari, Mastodon for iOS. 

### What happened?

I searched for a user, and picked to follow. 

### What you expected to happen?

After picking follow, I expect to see an “unfollow”. It shows pending instead. 

### How to reproduce it?

Search for remote user, open user profile, pick follow.

**Comment by tsmethurst** [comment] 2022-11-30 09:07
Thanks! I edited the title of this to reflect that it's not a regression specific to v0.6.0-rc1.

Some context on this to explain what's happening, and to help debug:

When you send a Follow to an account on a remote server, a follow request is put in your GtS database targeting that account. When you view the account via some client app, you'll then see the 'pending' status to indicate that a follow request exists in your database for that account.

In order for the follow request to be converted into a follow on your gts instance, the remote server has to send back an Accept activity with the URI of the Follow as an object, to indicate that the Follow has been Accepted. For accounts that are not 'locked', remote servers conventionally send the Accept back immediately.

In some cases, however, the remote server cannot or won't send the Accept back, even when the follow targets an unlocked account: sometimes there are database issues, or the remote server goes down for a bit and doesn't get the message, or it doesn't recognize the GtS server because of configuration/federation issues or some other bug.

Often, it's a good idea to try unfollowing and refollowing the remote account, if it's unlocked and you don't get a reply back immediately. If this still doesn't work, the next step is to investigate whether your gts server is set up properly, and that there are no issues with federation (are you using a different host/account-domain and haven't set up well-known forwarding properly for example). If this still doesn't work, it's possible you're trying to follow someone on a server software that has issues federating with GoToSocial.

Hope this helps a bit :)

**Comment by Fastidious** [comment] 2022-11-30 13:04
@tsmethurst thank you for the good explanation on how things work, and on what could be happening. Perhaps take the same approach at Pinafore? Each time I follow on it, it seems to provide the same feedback: success. I am not sure if that is the right thing to do, but sure makes me feel better! 😂

**Comment by tsmethurst** [comment] 2022-12-05 10:20
Since this isn't really a bug per se, I'm gonna close this issue for now. In future we might look at a better way of informing the user that their instance is waiting for an Accept from the remote instance, but I'll make a separate issue for that if/when we do it :)

**Closed by tsmethurst** 2022-12-05 10:20 UTC
Labels: bug, ux, federation
