### ISSUE TITLE
[bug] Video upload recorded with an iPhone results in 422 Unprocessable entity

### ISSUE THREAD

**Issue by kensanata** [superseriousbusiness/gotosocial#1688] opened 2023-04-10 17:10 UTC
### Describe the bug with a clear and concise description of what the bug is.

I'm on an iPhone 11 and use Toot! to upload a video somebody sent me from a newer iPhone. On the phone the info I see is:

- Apple iPhone 14 HEVC
- 1080p 1080×1920 25MB Dolby Vision
- 30 FPS
- 00:23

On the client, I'm getting a message that the upload failed.

On the server, config.yaml says `media-video-max-size: 41943040` so size should not be a problem.

The log file says:

timestamp="10/04/2023 17:09:02.737" func=middleware.Logger.func1.1 level=INFO latency=2.359508383s clientIP=… userAgent="Toot!/172 CFNetwork/1404.0.5 Darwin/22.3.0" method=POST statusCode=422 path=/api/v1/media requestID=b6abctw704000xr29nsg msg="Unprocessable Entity: wrote 650B"

Next, I shared the video to a mail that I sent to myself (which reduces the file size by a factor of 10), saved it again, and tried to upload that, from my iPhone 11, same problem. 

Next, I downloaded that file to my laptop running a Debian-derived operating system and used Pinafore to upload the video, same problem.

So this problem is unrelated to the client, or the operating system, but it's something about the video file itself. Encoding? I don't know.

https://user-images.githubusercontent.com/1145712/230953636-72abf70c-6539-41ca-b573-4bd985e6ea87.MOV

I attached the second, smaller file.

### What's your GoToSocial Version?

v0.7.1

### GoToSocial Arch

arm64 Binary

### What happened?

I get an error when uploading a short video.

### What you expected to happen?

The video to upload successfully.

### How to reproduce it?

No idea. But you can take a look at the video here: https://alexschroeder.ch/pics/IMG_3618.MOV

### Anything else we need to know?

Nope.

**Comment by kensanata** [comment] 2023-04-10 17:19
Doing some re-encoding myself results in an MP4 file that I can upload (using Pinafore, same setup that fails with the MOV file).

```sh
ffmpeg -i IMG_3618.MOV -q:v 0 IMG_3618.MP4
```

**Comment by NyaaaWhatsUpDoc** [comment] 2023-04-10 19:53
The issue is that for now we only support `mp4` :)

**Comment by kensanata** [comment] 2023-04-11 08:16
Ah, that explains it. Would it be possible to say this in the 422 message and the log? That would have helped me understand what is happening, at least. Something like: “422 Video format not supported (currently supported: video/mpg4)” – or whatever the correct wording would be? Perhaps this can then be extended over time.

Some clients might show the message text, and I would have found it in the logs for sure.

**Comment by erasmas** [comment] 2023-06-13 20:20
Surprisingly, I'm not able to upload an MP4 video either. The video is recorded on iPhone and converted to MP4 specifically for gotosocial but I'm getting HTTP 422. 😕

**Comment by Ben02** [comment] 2023-07-12 11:43
I'm not able to upload an MP4 video which is a screen record by iOS. I got HTTP 422 too.

**Comment by tsmethurst** [comment] 2023-08-07 08:17
For future reference, there's a list here of box types that are and aren't currently supported: https://github.com/abema/go-mp4/issues/13

**Comment by erasmas** [comment] 2023-08-16 08:19
Verified that this issue is still present in 0.11.0. Is there any information that I can provide to help with the fix?

**Comment by tsmethurst** [comment] 2024-07-15 10:01
This should be closed by https://github.com/superseriousbusiness/gotosocial/issues/1688 (tested with the video in the OP)

**Closed by tsmethurst** 2024-07-15 10:01 UTC
Labels: bug
