### ISSUE TITLE
[feature] Some improvements of the Domain Permissons UI

### ISSUE THREAD

**Issue by coxde** [superseriousbusiness/gotosocial#3091] opened 2024-07-10 09:31 UTC
### Is your feature request related to a problem ?

Hiya! Currently, domains are sorted alphabetically in Domain Blocks/Allows, it might be clearer if they were sorted by last update time.

Also, the domain list is currently a fixed container. It might be easier to navigate when there are many domains if it were flexible or even paged.

### Describe the solution you'd like.

1. Different sorted method of domain list (alphabetically, chronologically)
2. Resizable list container or a paged container

### Describe alternatives you've considered.

Not really

**Comment by tsmethurst** [comment] 2024-07-10 13:07
Hiya, this issue is mostly a duplicate of https://github.com/superseriousbusiness/gotosocial/issues/3004 so I'll close it.

When we add sortable-by-creation-time to domain permissions, we'll probably look at adding paging as well.

**Closed by tsmethurst** 2024-07-10 13:07 UTC
Labels: enhancement
