### ISSUE TITLE
Support Ivory

### ISSUE THREAD

**Issue by kyleconroy** [superseriousbusiness/gotosocial#1384] opened 2023-01-24 20:35 UTC
_This is a placeholder issue for now that I'll add to more as I debug this issue_

[Ivory](https://tapbots.com/ivory/) for iOS recently launched in [early access](https://tapbots.social/@ivory/109745562673796762). I'm struggling to use Ivory with my GTS instance. The app crashes on launch after making the following requests:

```
timestamp="24/01/2023 20:53:06.479" func=router.loggingMiddleware.func1 level=INFO latency=1.096251ms clientIP=99.124.152.180 userAgent="Ivory/10000 CFNetwork/1402.0.8 Darwin/22.2.0" method=GET statusCode=200 path=/api/v1/lists msg="OK: wrote 26B"
timestamp="24/01/2023 20:53:06.482" func=router.loggingMiddleware.func1 level=INFO latency=2.343475ms clientIP=99.124.152.180 userAgent="Ivory/10000 CFNetwork/1402.0.8 Darwin/22.2.0" method=GET statusCode=404 path=/api/v1/accounts/20 msg="Not Found: wrote 767B"
timestamp="24/01/2023 20:53:06.483" func=router.loggingMiddleware.func1 level=INFO latency=875.152µs clientIP=99.124.152.180 userAgent="Ivory/10000 CFNetwork/1402.0.8 Darwin/22.2.0" method=GET statusCode=200 path=/api/v1/accounts/20/statuses msg="OK: wrote 26B"
timestamp="24/01/2023 20:53:06.508" func=router.loggingMiddleware.func1 level=INFO latency=6.183327ms clientIP=99.124.152.180 userAgent="Ivory/10000 CFNetwork/1402.0.8 Darwin/22.2.0" method=GET statusCode=302 path=/fileserver/020XPYF5HVQD43WQCZSRR76PHH/attachment/small/01HCHKE5JFWCWEKJ6HYYD4KVW4.jpeg msg="Found: wrote 488B"
timestamp="24/01/2023 20:53:06.510" func=router.loggingMiddleware.func1 level=INFO latency=26.555225ms clientIP=99.124.152.180 userAgent="Ivory/10000 CFNetwork/1402.0.8 Darwin/22.2.0" method=GET statusCode=200 path=/api/v1/timelines/home msg="OK: wrote 7.26kiB"
timestamp="24/01/2023 20:53:06.545" func=router.loggingMiddleware.func1 level=INFO latency=752.888µs clientIP=99.124.152.180 userAgent="Ivory/10000 CFNetwork/1402.0.8 Darwin/22.2.0" method=GET statusCode=302 path=/fileserver/020XPYF5HVQD43WQCZSRR76PHH/attachment/small/01HCHKE5JFWCWEKJ6HYYD4KVW4.jpeg msg="Found: wrote 488B"
```

I'm not sure if this in an Ivory issue or a GoToSocial issue.

**Comment by f0x52** [comment] 2023-01-24 20:58
closing as duplicate of https://github.com/superseriousbusiness/gotosocial/issues/1339, if you find any new details feel free to add them there

**Closed by f0x52** 2023-01-24 20:58 UTC
