### ISSUE TITLE
[bug] outgoing HTTP proxy

### ISSUE THREAD

**Issue by atomotic** [superseriousbusiness/gotosocial#2341] opened 2023-11-08 18:54 UTC
### Describe the bug with a clear and concise description of what the bug is.

I'm trying to [proxy outgoing traffic](https://docs.gotosocial.org/en/latest/advanced/outgoing-proxy/) through a proxy, but seems that HTTPS_PROXY [ENV](https://github.com/superseriousbusiness/gotosocial/blob/main/internal/httpclient/client.go#L167) doesn't have any effect.

The proxy is working fine, I've tried several curl commands or other http clients.
What else should I try?

I'm running Gotosocial this way:

```
HTTPS_PROXY={MY_PROXY}:8999 ./gotosocial server start
```

### What's your GoToSocial Version?

v0.12.0 git-9b76afc

### GoToSocial Arch

arm64 Binary

**Comment by tsmethurst** [comment] 2023-11-08 22:26
Heya

> {MY_PROXY}:8999

Is that including a protocol, or just host:port? Did you try it with/without a protocol? Could you try using `HTTP_PROXY` instead of `HTTPS_PROXY` and see if that helps? I've never used GtS with a proxy myself, so not sure which one ought to work; we just use the Go HTTP client's standard proxy functionality, from which our documentation is prettymuch copy-pasted.

**Comment by atomotic** [comment] 2023-11-11 07:13
nope, neither using protocol or http_proxy works.
I will try other tricks, maybe [proxychains](https://github.com/rofl0r/proxychains-ng).
It's not urgent, I will look better in the code too. Thanks

**Comment by daenney** [comment] 2023-11-27 08:27
We set `ProxyFromEnvironment` on the HTTP clients we create so this should work: https://github.com/superseriousbusiness/gotosocial/blob/c334df8f432e22c5d462b98faee2b7e32d59bed6/internal/httpclient/client.go#L166-L178

The format needs to follow Go's documentation, but it's pretty industry standard:

> The environment values may be either a complete URL or a "host[:port]", in which case the "http" scheme is assumed. The schemes "http", "https", and "socks5" are supported. An error is returned if the value is a different form.
>
> https://pkg.go.dev/net/http#ProxyFromEnvironment

Are you sure the `HTTP(S)_PROXY` variables are set in the context of the process? For example, if you're starting with systemd, did you add `Environment=` directives to the unit file? You can also verify this by first finding the GtS process ID (something like `ps aux | grep -i gotosocial`) and then checking it's environment with `cat /proc/$id/environ`.

**Comment by tsmethurst** [comment] 2024-01-22 14:18
Hi, did you ever get this resolved? Should I close this issue?

**Comment by atomotic** [comment] 2024-01-24 07:39
Sorry, I didn't try any further, the project I was working on was postponed.

**Comment by daenney** [comment] 2024-01-26 11:54
So I modified the GoToSocial binary for a second to print `os.Environ` as early as possible in our startup, before we even do config parsing:

```
$ env HTTPS_PROXY=https://localhost:8000 ./gotosocial server start
```
```
[]string{"HTTPS_PROXY=https://localhost:8000"}
```

It definitely ends up there, so bar a bug in the Go standard library I don't see how the value wouldn't propagate. As far as I can tell, we construct the client transport correctly and we do set `ProxyFromEnvironment` on the HTTP transport we create for the client.

I don't have another way to test this and since everything I can see suggests this should work, I'm going to go ahead and close this for now. If you eventually get back to your project and the issue still reproduces, feel free to reopen the issue.

**Closed by daenney** 2024-01-26 11:54 UTC
Labels: bug
