### ISSUE TITLE
[feature] Store remote media separately from local media

### ISSUE THREAD

**Issue by gaykitty** [superseriousbusiness/gotosocial#2739] opened 2024-03-10 04:39 UTC
### Is your feature request related to a problem ?

When backing up GtS's media store, it would be nice to be able to only back up local media as remote media can be required.

### Describe the solution you'd like.

A option to store remote media separately from local media. For instance, in a separate directory.

### Describe alternatives you've considered.

I have not thought of alternative solutions, but I'm open to other ideas that'd make backing up local media only possible.

**Comment by tsmethurst** [comment] 2024-03-10 10:13
This is a dupe of https://github.com/superseriousbusiness/gotosocial/issues/1776 so I'll close it.

Agreed that it would be good to have, we just haven't got around to doing it yet.

**Closed by tsmethurst** 2024-03-10 10:13 UTC
Labels: enhancement
