### ISSUE TITLE
[bug] Mastodon user can't resolve post URLs for followers only/private posts made on GoToSocial

### ISSUE THREAD

**Issue by JacksonChen666** [superseriousbusiness/gotosocial#3177] opened 2024-08-05 22:37 UTC
### Describe the bug with a clear and concise description of what the bug is.

It is possible to open up a remote/local post by taking the URL of it, putting into the search bar in your fedi client, and pressing enter. (At least on Mastodon and GoToSocial). This allows interacting with a post and stuff.

When an account on a GoToSocial instance makes a followers only or mentioned only post, a Mastodon user trying to use the search function with the URL will get no results, even if the Mastodon user has is allowed to view that post (via mentions or following the GoToSocial user).

### What's your GoToSocial Version?

v0.16.0+git-f1cbf6f

### GoToSocial Arch

amd64 (self-compiled) binary

### What happened?

As described in the description, nothing shows up in the search results.

### What you expected to happen?

The Mastodon user should be allowed to look up the post via URL (under the presumption that the Mastodon user is allowed via mentions or following).

### How to reproduce it?

0. Mastodon user follows GtS user
1. GtS user makes a post that is either followers only, or mentioned people only (with the Mastodon user mentioned)
2. Mastodon user receives the post, and saves the URL for possible later reference. Mastodon user later puts the URL into the search bar to open it up again, and searches for it
4. Mastodon user gets no results.

### Anything else we need to know?

- This issue has not been reported to Mastodon
- This issue hasn't been tested with Vanilla Mastodon yet, only [glitch-soc]
    - This was tested with catcatnya.com ([v4.3.0-alpha.5+glitch+cat+1.0.7](https://github.com/CatCatNya/catstodon/releases/tag/v4.3.0-alpha.5%2Bglitch%2Bcat%2B1.0.7)) and micro.jacksonchen666.com ([741e218](https://git.sr.ht/~jacksonchen666/glitch-soc-mastodon-fork/commit/741e218f65264697ef454c6896a0e5cb76713b03)).
    
      Both instances are a different soft-fork of [glitch-soc], with catcatnya.com making its own and micro.jacksonchen666.com using a soft-fork of [wetdry.world's Mastodon source code](https://github.com/TheEssem/mastodon) (which is a soft-fork of [glitch-soc]).
- A GtS user can resolve via URL a followers only/private post made by a GtS user.
- The URL being used in the search is the remote instance's URL (e.g. `https://gts.example/@username/statuses/0BCDEFGHIJKLMNOPQRSTUVWXYZ`), not the local instance's URL (e.g. `https://mastodon.example/deck/@user@gts.example/123456789012345678`).
- I have not looked for logs on either side or the client side.
- This issue was seen in the wild with 2 different GtS instances running both `0.16.0+git-f1cbf6f`.

[glitch-soc]:https://github.com/glitch-soc/mastodon

**Comment by tsmethurst** [comment] 2024-08-05 22:51
I'll check this properly tomorrow and look at logs to confirm, but I believe this may be because Mastodon uses their instance actor to try to resolve remote URLs, and GoToSocial is likely denying the request with 404 or 403 or something similar, because the Mastodon instance actor doesn't follow the author of the followers-only status. If I'm right about that, that means this is a Mastodon issue and not a GtS one, but like I said, I'll get back to you.

**Comment by tsmethurst** [comment] 2024-08-05 22:54
(Actually if you feel up for it, you could confirm this by checking the logs of your GtS instance while the Mastodon user makes their request, and see which pubKeyID the request is signed with, and what your GtS instance is returning.)

**Comment by tsmethurst** [comment] 2024-08-06 07:44
As I thought yeah, so Masto is using the instance actor, GtS says no because the instance actor doesn't have the right to see it. From GtS's side this is working as intended.

**Comment by tsmethurst** [comment] 2024-08-06 09:57
I see there's already an issue open for this on Mastodon -- https://github.com/mastodon/mastodon/issues/8193 -- so I'm going to close this from our side.

**Closed by tsmethurst** 2024-08-06 09:57 UTC
Labels: bug
