### ISSUE TITLE
[bug] 500 ISE on posting

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#1008] opened 2022-11-09 00:24 UTC
### Describe the bug with a clear and concise description of what the bug is.

I get a 500 Internal Server Error on posting something.

Log:

```
@40000000636af1dd1084ad04 timestamp="09/11/2022 00:18:27.276" func=router.loggingMiddleware.func1 level=ERROR latency=32.315051ms clientIP=2001:4dd7:3371:0:21f:3bff:fe0d:cbb1 userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" method=POST statusCode=500 path=/api/v1/statuses error="Error #01: ERROR: unterminated quoted string at or near \"'<p><span class=\"h-card\"><a href=\"https://mastodon.social/@Alisca\" class=\"u-url mention\" rel=\"nofollow noreferrer noopener\" target=\"_blank\">@<span>Alisca</span></a></span> Mr “Schei�\" (SQLSTATE 42601)\n" msg="Internal Server Error: wrote 54B"
```

The request (according to Firebug, or whatever this is called now) was:

```
{"status":"@Alisca@mastodon.social Mr “Schei� Encoding” has, unfortunately, died.","in_reply_to_id":"01CQE88MJ0M72BZ60JSMTFYWXQ","visibility":"unlisted"}
```

I think you’re misprocessing the U+FFFD here.

### What's your GoToSocial Version?

0.5.2 git-c31f219

### GoToSocial Arch

amd64 binary

### Browser version

firefox-esr     102.4.0esr-1~deb11u1

### What happened?

500 instead of posting

### What you expected to happen?

Posting instead of 500

### How to reproduce it?

Post a single U+FFFD character, not even as reply, is sufficient.

I expect to be able to post all valid UCS codepoints, that is:

- from C0 control characters, at least U+0009 and U+000A
- U+0020‥U+007E
- U+00A0‥U+D7FF
- U+E000‥U+FFFD
- U-00010000‥U-0010FFFD with the exception of U-????FFFE and U-????FFFF

**Comment by NyaaaWhatsUpDoc** [comment] 2022-11-09 00:29
Thanks for reporting! That is an interesting one... Possibly a result of passing through a combination of libraries during string sanitizing. Will get on that :)

**Comment by tsmethurst** [comment] 2022-11-10 10:40
This looks like an error is being returned by the database, and then by https://github.com/uptrace/bun -- the ORM that we use.

**Comment by tsmethurst** [comment] 2022-11-10 11:08
Aha okay thanks!

**Comment by mirabilos** [comment] 2022-11-10 11:16
There were no instructions on with what parameters to create the database, so I just used sensible defaults:

```
    Name    |   Owner    | Encoding  | Collate |  Ctype  |   Access privileges   
------------+------------+-----------+---------+---------+-----------------------
 another    | another    | SQL_ASCII | C       | C       | 
 gotosocial | gotosocial | UTF8      | C.UTF-8 | C.UTF-8 | 
```

The `another` database is what I generally use, for speed, if I know the application is not caring about the encoding of the data in the database (as relates to use in queries) and does its own thing, but I defaulted to “safer” settings here.

**Comment by mirabilos** [comment] 2022-12-12 14:59
view online
[https://opencollective.com/gotosocial/updates/november-december-updates]

GoToSocial logo
[https://res.cloudinary.com/opencollective/image/fetch/h_96,c_fill/f_png/https%3A%2F%2Fopencollective-production.s3.us-west-1.amazonaws.com%2Fb7ea3c00-d05d-11ec-b128-272e4ec05dbd.png]
[https://opencollective.com/gotosocial]


GOTOSOCIAL

[https://opencollective.com/gotosocial]



NOVEMBER / DECEMBER UPDATES

by tobi [https://opencollective.com/tsmethurst]
Hello everyone! Welcome to the extremely irregular GoToSocial newsletter!


v0.6.0 Soothing Sloth 


In November we had a very busy and exciting month, which culminated in the
release of v0.6.0 Soothing Sloth last week. :) This was our biggest release so
far, and included a wacky amount of fixes and new things. Thanks again to
everyone who helped us by contributing code, opening issues, helping others out
in the help channels, and supporting us with money and encouragement! 

If you haven't tried out the release yet, you can grab it here:
https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.6.0
[https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.6.0] 

NLnet and 2023 roadmap 


We also spent a bunch of time in the last couple of weeks making a
**SPREADSHEET** for the features and research we're going to do thanks to the
50k Euro funding grant we received from NLnet. 

We had to jiggle the roadmap around to make things fit on there with the budget
we have. We'll release an updated version of that roadmap soon(tm) so you can
see what we've got planned for 2023! 


GtS is becoming A Thing 


This last month also saw a big rise in the amount of attention that GoToSocial
has been getting from people. We went from about 800 stars on our Github repo to
almost 2,000 stars. 


The amount of GoToSocial servers deployed in the wild also increased hugely the
last month, as you can see from the graph below (source
https://gotosocial.fediverse.observer/stats
[https://opencollective.com/redirect?url=https%3A%2F%2Fgotosocial.fediverse.observer%2Fstats]): 


 [https://opencollective-production.s3.us-west-1.amazonaws.com/4d4b7060-7a2d-11ed-b73c-a3fa516a64be.png]
[https://opencollective-production.s3.us-west-1.amazonaws.com/4d4b7060-7a2d-11ed-b73c-a3fa516a64be.png]
Image description: A graph of GoToSocial servers online per month. In the last
two months, the amount of deployed servers has spiked from 150 to about 500,
creating a sharp incline in the graph. 


This has been cool, but also a little overwhelming! Which leads to our next
point... 

We're taking a little holiday 

From 19 December to 02 January, we're going to be closing shop. What this
means: 


- We'll make the Github repository read-only for those two weeks so no new
issues or PRs can be opened (except by the core team, if they're suddenly
possessed by a fervor to work for some reason). 

- We'll make the channels in the Matrix space read-only too, so you can still
scroll through messages in the help channel, for example, but you won't be able
to post anything new there. 


This will give us some time to chill out, see friends, do some knitting, play
video games, and take some wintery walks. Sloths need breaks too! 

--- 


So, that's it from us! Thanks again for a wild last few months of the year, and
we look forward to updating you again in 2023 :) 


-- tobi, kim, f0x & maloki 

--------------------------------------------------------------------------------

Comment
[https://opencollective.com/gotosocial/updates/november-december-updates]

***@***.***
[https://opencollective.com]

We can do great things together

To unsubscribe from notifications of new updates from this collective, click
here
[https://opencollective.com/email/unsubscribe/reply%2Baagshfv2tubduwaabutexyobpatqtevbnhhflzonlq%40reply.github.com/gotosocial/collective.update.published/e0f3806d6544637aba6d5a2324d4b01af6df3992b507374184010af6e9f8eb133eb26a08992b8dc59b07655f2fc3ec1273e0995b1e49f135e567aa5f5cb7398f]

You can also follow us on Twitter [https://twitter.com/OpenCollect] or come chat
with us on our public Slack channel [https://slack.opencollective.com].

Made with ❤️ from all over the world
[https://docs.opencollective.com/help/about/team]

**Comment by tsmethurst** [comment] 2023-03-31 13:27
hey @mirabilos, can you still reproduce this one? just wanted to check on it

**Comment by mirabilos** [comment] 2023-07-21 01:17
I can post U+FFFD � now, in 0.10.0-rc3 git-f431974 (but I haven’t tested the over a million other codepoints).

**Comment by tsmethurst** [comment] 2023-07-21 09:01
I'll close this now then, since we can't realistically test the million other codepoints. If it comes up again, we can reopen the issue.

**Closed by tsmethurst** 2023-07-21 09:01 UTC
Labels: bug

**Comment by mirabilos** [comment] 2023-07-21 13:45
tobi dixit:

>I'll close this now then, since we can't realistically test the million
>other codepoints. If it comes up again, we can reopen the issue.

That’s what I was thinking, but I wanted to leave the actual closing
to you.

Thanks!
