### ISSUE TITLE
[feature] persist the timing state of `media-cleanup-every`

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#3045] opened 2024-06-26 21:06 UTC
### Is your feature request related to a problem ?

It seems that the timer for `media-cleanup-every` get reset every time a gotosocial instance restarts. If this is true, it means that the media auto-cleanup will never take effect if the value of `media-cleanup-every` is greater than the interval at which the user update their GTS instance.

Is it possible to save the timer for `media-cleanup-every`, so that the GTS instance can have the `media-cleanup-every` interval set freely even in the case of frequent updates?

p.s. will #3042 fix this issue?

### Describe the solution you'd like.

Persist the timing state of `media-cleanup-every` to db.

### Describe alternatives you've considered.

It would also be helpful to add a corresponding note in the documentation.

### Additional context.

Specifically, my GTS instance restarts approximately every 24 hours due to updates. After setting media-cleanup-every to 168h, my storage keeps increasing and seems to never be cleaned up.

**Comment by tsmethurst** [comment] 2024-06-29 07:02
Just realized this is a duplicate of https://github.com/superseriousbusiness/gotosocial/issues/2492, so I'll close this one. In the meantime, perhaps you could try just restarting GtS once every 8 days or so, to ensure the media cleanup runs, that would at least prevent your media size from getting out of control while we figure something out for storing the timing of jobs.

**Closed by tsmethurst** 2024-06-29 07:02 UTC
Labels: enhancement

**Comment by CDN18** [comment] 2024-06-29 08:37
Thanks, Will follow #2492 then :)
