### ISSUE TITLE
[feature] Display list of registered applications and allow revoking access

### ISSUE THREAD

**Issue by lmas** [superseriousbusiness/gotosocial#1643] opened 2023-03-23 11:15 UTC
### Is your feature request related to a problem ?

Missing a way to review registered 3rd party applications and allow revoking their access to the instance. 

### Describe the solution you'd like.

Add a "Applications" page to the admin site, which display a list of registered applications and have a "revoke/disable/delete" button for each one.

### Describe alternatives you've considered.

Some kind of admin `/revoke/application` API endpoint but after a quick look around there doesn't seem to be an officially documented endpoint, for mastodon in general.

**Comment by tsmethurst** [comment] 2023-04-03 15:08
If it's OK with you, I'm gonna close this one as more or less a duplicate of #1573 , wherein we already have some links to other issues. Feel free to reopen it if there's more you wanna discuss here :)

**Closed by tsmethurst** 2023-04-03 15:08 UTC
Labels: enhancement
